services:
  db:
    image: postgres:16
    container_name: tonshooter_db
    environment:
      POSTGRES_USER: tonshooter
      POSTGRES_PASSWORD: tonshooter
      POSTGRES_DB: tonshooter
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
